language: python
python:
- 3.6
- 3.5
- 3.4
- 2.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: makarand-mac
  password:
    secure: HPnPmfFPna57Iil2FlyeQVCo98uquBSezNrgxuh596qf/mPgh34yZYwM+B9z4R8ATDehoDnyPmdBCd6mHZuGO8cjrLhxjLFXu28IwiYXHcdcNi7YKLtvp6f0bcP/CW97eE7QJchDRpzHFNidK2+fEfVkjolP4vG4zlC8nUwevyEaS7/J8lzquhDJExs1YRD5/nMS9fBl9lYZjqKBck6ULniHd4enXhEfKNQV7dicAOIGdXMiNX8oQa2Hh1WIeSCsTWuqSiXpIRgkDXd1v1mRQw/2j9HQdQNyhY2VHsLWxYCNM0haCt/GjKUdq2wcmzQ/LWjW2glh6lUa03geSzWsebHLOM7zET891MjWvke7aT1dF1MLo6GbcjLUDf0aGlfJzJnuPRpaoFpK2Ggvpep6fD3c5yVPWY9ZHWoFo4ZchIfHFtgIAh8soPj4iG4t1oclG9w6GyzvXXu9bFpXDx3fMkZcVRfen4UcKFZUNq569X7qVNd/D7heucn9NfE8CW+RDao47Gt17vEbHlDpKxLLu5RUt/UDND7DBhdxUuUyRptEb1/HiQUoNaww2YG/zjmTd7UYkVY8UjBd19H+EfCAQRwG73O3+a+ha3skxGVYKyWN8NUJV19eyq+UYvva/+uyl5GdkGog6Gk/TAge8FXaYxH0wDnLbrNYoACL4KQNQFU=
  on:
    branch: master
    tags: true
    repo: the-procedure/textlocal-python
    python: 3.6
